spring.application.name=keyvault

spring.datasource.url=jdbc:sqlite:database.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

logging.level.nasa.keyvault=TRACE

jwt.secret=your-secret
jwt.expiration-ms=10800000

vault.master=

otp.duration-ms=300000
otp.message-template=Your one time passcode is: %s. Do not share this code with anybody, we will never ask for it.
